# DSC 80: Project 01

### Checkpoint Due Date: Thursday April 9, 11:59:59 PM (Questions 1-4)
### Due Date: Thursday, April 16, 11:59:59 PM

---
# Instructions

This Jupyter Notebook contains the statements of the problems and provides code and markdown cells to display your answers to the problems.  
* Like the lab, your coding work will be developed in the accompanying `project01.py` file, that will be imported into the current notebook. This code will be autograded.
* **For the checkpoint, turn in questions 1-4**

**Do not change the function names in the `*.py` file**
- The functions in the `*.py` file are how your assignment is graded, and they are graded by their name. The dictionary at the end of the file (`GRADED FUNCTIONS`) contains the "grading list". The final function in the file allows your doctests to check that all the necessary functions exist.
- If you changed something you weren't supposed to, just use git to revert!

**Tips for developing in the .py file**:
- Do not change the function names in the starter code; grading is done using these function names.
- Do not change the docstrings in the functions. These are there to tell you if your work is on the right track!
- You are **encouraged to write your own additional functions** to solve the questions! 
    - Developing in python usually consists of larger files, with many short functions.
    - You may write your other functions in an additional `.py` file that you import in `project01.py` -- however, be sure to upload these to gradescope as well!
- Always document your code!

**Tips for testing the correctness of your answers!**
Once you have your work saved in the .py file, you should import the `project01` to test your function out in the notebook. In the notebook you should inspect/analyze the output to assess its correctness!
* Run your functions on the main dataset (`grades`) and ask yourself if the output *looks correct.*
* Run your functions on very small datasets (e.g. 1-5 row table), calculate the expected response by hand, and see if the function output matches (this *is* unit-testing your code with data).
* Run your functions on (large and small) samples of the dataset `grades` (with and without replacement). Does your code break? Or does it still run as expected.

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import project01 as proj

In [3]:
%matplotlib inline
import pandas as pd
import numpy as np

import os

# The Other Side of Gradescope

The file contains the grade-book from a fictional data science course with 535 students. 

**Note: this dataset is synthetically generated; it does not contain real student grades.**

In this project, you will:
1. clean and process the data to compute total course grades according to a fictional syllabus (below),
2. qualitatively understand how students did in the course,
3. understand how student grades vary with small changes in performance on each assignment.

---

The course syllabus is as follows:

* Lab assignments 
    - Each are worth the same amount, regardless of each lab's raw point total.
    - The lowest lab is dropped.
    - Each lab may be revised for one week after submission for a 10% penalty, for two weeks after submission for a 20% penalty, and beyond that for a 50% penalty. Such revisions are reflected in the `Lateness` columns in the gradebook.
    - Labs are 20% of the total grade.
* Projects 
    - Each project consists of an autograded portion, and *possibly* a free response portion.
    - The total points for a single project consist of the sum of the raw score of the two portions.
    - Each are worth the same amount, regardless of each project's raw point total.
    - Projects are 30% of the total grade.
* Checkpoints
    - Project checkpoints are worth 2.5% of the total grade.
* Discussion
    - Discussion notebooks are worth 2.5% of the total grade.
* Exams
    - The midterm is worth 15% of the total grade.
    - The final is worth 30% of the total grade.

### A note on generalization

You may assume that your code will only need to work on a gradebook for a class with the syllabus given above. That is, you may assume that the dataframe `grades` looks like the given one in `data/grades.csv`.

However, such a class:
1. may have a different numbers of labs, projects, discussions, and project checkpoints.
2. may have a different number of students.

You may assume the course components and the naming conventions are as given in the data file.

The dataset was generated by Gradescope; you must attempt to reason about the data as given using what you know as a student who uses Gradescope.

### A note on 'putting everything together'

The goal of this project is to create and assess final grades for a fictional course; if anything, the process is broken down into functions for your convenience and guidance. Here are a few remarks and tips for approaching the projects:
1. If you are having trouble figuring out what a question is asking you to do, look at the big picture and try to understand what the current step is doing to contribute to this big picture. This may clarify what's being asked!
1. These questions intentionally build off of each other and the final result matters! In fact, you can 'get a question correct', but only receive partial credit on it because a previous answer was wrong.
    - Credit for a question will typically receive partial credit based on *how close* your answer is to correct (as well as some credit for a solution in the correct form). 
    - You should try to assess your answer to each question based on what you understand of the data. This might involve writing extensive code (that isn't turned in) just to check your work! Suggestions on checking your work are given in the assignment, but you should also think of your own ways of checking your work.
    - As you do this project, think about the data from the perspective of the student (which should be easy to do!)

In [4]:
grades_fp = os.path.join('data', 'grades.csv')
grades = pd.read_csv(grades_fp)

### Getting started: enumerating the assignments

First, you will list all the 'assignment names' and what part of the syllabus to which they belong.

**Question 1:**

Create a function `get_assignment_names` that takes in a dataframe like `grades` and returns a dictionary with the following structure:
- The keys are the general areas of the syllabus: `lab, project, midterm, final, disc, checkpoint`
- The values are lists that contain the assignment names of that type. For example the lab assignments all have names of the form `labXX` where `XX` is a zero-padded two digit number. See the doctests for more details.

In [23]:
def get_assignment_names(grades):
    '''
    get_assignment_names takes in a dataframe like grades and returns 
    a dictionary with the following structure:

    The keys are the general areas of the syllabus: lab, project, 
    midterm, final, disc, checkpoint

    The values are lists that contain the assignment names of that type. 
    For example the lab assignments all have names of the form labXX where XX 
    is a zero-padded two digit number. See the doctests for more details.    

    :Example:
    >>> grades_fp = os.path.join('data', 'grades.csv')
    >>> grades = pd.read_csv(grades_fp)
    >>> names = get_assignment_names(grades)
    >>> set(names.keys()) == {'lab', 'project', 'midterm', 'final', 'disc', 'checkpoint'}
    True
    >>> names['final'] == ['Final']
    True
    >>> 'project02' in names['project']
    True
    '''
    cols = grades.columns
    keys = ['lab', 'project', 'midterm', 'final', 'disc', 'checkpoint']
    assignment_dict = dict.fromkeys(keys)
    assignment_dict['lab'] = [x for x in cols if 'lab' in x and '-' not in x]
    assignment_dict['project'] = [x for x in cols if 'project' in x and '-' not in x and '_' not in x]
    assignment_dict['midterm'] = [x for x in cols if 'Midterm' in x and '-' not in x]
    assignment_dict['final'] = [x for x in cols if 'Final' in x and '-' not in x]
    assignment_dict['disc'] = [x for x in cols if 'disc' in x and '-' not in x]
    assignment_dict['checkpoint'] = [x for x in cols if 'checkpoint' in x and '-' not in x]
    
    
    return assignment_dict

In [24]:
names = get_assignment_names(grades)
set(names.keys()) == {'lab', 'project', 'midterm', 'final', 'disc', 'checkpoint'}

True

In [25]:
names['final'] == ['Final']
# 'project02' in names['project']

True

In [26]:
grades.columns

Index(['PID', 'College', 'Level', 'lab01', 'lab01 - Max Points',
       'lab01 - Lateness (H:M:S)', 'lab02', 'lab02 - Max Points',
       'lab02 - Lateness (H:M:S)', 'project01', 'project01 - Max Points',
       'project01 - Lateness (H:M:S)', 'lab03', 'lab03 - Max Points',
       'lab03 - Lateness (H:M:S)', 'project01_free_response',
       'project01_free_response - Max Points',
       'project01_free_response - Lateness (H:M:S)', 'lab04',
       'lab04 - Max Points', 'lab04 - Lateness (H:M:S)', 'lab05',
       'lab05 - Max Points', 'lab05 - Lateness (H:M:S)',
       'project02_checkpoint01', 'project02_checkpoint01 - Max Points',
       'project02_checkpoint01 - Lateness (H:M:S)', 'Midterm',
       'Midterm - Max Points', 'Midterm - Lateness (H:M:S)', 'lab06',
       'lab06 - Max Points', 'lab06 - Lateness (H:M:S)',
       'project02_checkpoint02', 'project02_checkpoint02 - Max Points',
       'project02_checkpoint02 - Lateness (H:M:S)', 'lab07',
       'lab07 - Max Points', 'lab07 - Lateness (H:M:S)', 'project02',
       'project02 - Max Points', 'project02 - Lateness (H:M:S)',
       'project02_free_response', 'project02_free_response - Max Points',
       'project02_free_response - Lateness (H:M:S)', 'lab08',
       'lab08 - Max Points', 'lab08 - Lateness (H:M:S)', 'lab09',
       'lab09 - Max Points', 'lab09 - Lateness (H:M:S)',
       'project03_checkpoint01', 'project03_checkpoint01 - Max Points',
       'project03_checkpoint01 - Lateness (H:M:S)', 'project03',
       'project03 - Max Points', 'project03 - Lateness (H:M:S)', 'Final',
       'Final - Max Points', 'Final - Lateness (H:M:S)',
       'Total Lateness (H:M:S)', 'project05_free_response',
       'project05_free_response - Max Points',
       'project05_free_response - Lateness (H:M:S)', 'project04',
       'project04 - Max Points', 'project04 - Lateness (H:M:S)', 'project05',
       'project05 - Max Points', 'project05 - Lateness (H:M:S)',
       'discussion01', 'discussion01 - Max Points',
       'discussion01 - Lateness (H:M:S)', 'discussion02',
       'discussion02 - Max Points', 'discussion02 - Lateness (H:M:S)',
       'discussion03', 'discussion03 - Max Points',
       'discussion03 - Lateness (H:M:S)', 'discussion04',
       'discussion04 - Max Points', 'discussion04 - Lateness (H:M:S)',
       'discussion05', 'discussion05 - Max Points',
       'discussion05 - Lateness (H:M:S)', 'discussion06',
       'discussion06 - Max Points', 'discussion06 - Lateness (H:M:S)',
       'discussion07', 'discussion07 - Max Points',
       'discussion07 - Lateness (H:M:S)', 'discussion08',
       'discussion08 - Max Points', 'discussion08 - Lateness (H:M:S)',
       'discussion09', 'discussion09 - Max Points',
       'discussion09 - Lateness (H:M:S)', 'discussion10',
       'discussion10 - Max Points', 'discussion10 - Lateness (H:M:S)'],
      dtype='object')

### Computing project grades

**Question 2**

Compute the total score for the project portion of the course according to the syllabus. Create a function `projects_total` that takes in `grades` and computes the total project grade for the quarter according to the syllabus. The output Series should contain values between 0 and 1.

*Note*: Don't forget to properly handle students who didn't turn in assignments! (Use your experience and common sense).

*Note:* To check your work, try (1) calculating the score for a few types of students by hand, and (2) calculate the statistics for the class performance on each individual course project, making sure they look reasonable.

In [27]:
grades.head()

,PID,College,Level,lab01,lab01 - Max Points,lab01 - Lateness (H:M:S),lab02,lab02 - Max Points,lab02 - Lateness (H:M:S),project01,...,discussion07 - Lateness (H:M:S),discussion08,discussion08 - Max Points,discussion08 - Lateness (H:M:S),discussion09,discussion09 - Max Points,discussion09 - Lateness (H:M:S),discussion10,discussion10 - Max Points,discussion10 - Lateness (H:M:S)
0,A14721419,SI,JR,99.0,100.0,00:00:00,86.0,100.0,00:00:00,75.0,...,00:00:00,10.0,10,00:00:00,10.0,10,780:01:28,10.0,10,00:00:00
1,A14883274,TH,JR,98.0,100.0,00:00:00,52.0,100.0,00:00:00,53.0,...,669:12:21,7.0,10,00:00:00,7.0,10,00:00:00,8.0,10,00:00:00
2,A14164800,SI,SR,86.0,100.0,00:00:00,45.0,100.0,00:00:00,44.0,...,00:00:00,6.0,10,00:04:51,6.0,10,00:00:00,7.0,10,00:00:00
3,A14847419,TH,JR,100.0,100.0,00:00:00,100.0,100.0,00:00:00,78.0,...,00:00:00,10.0,10,00:00:00,10.0,10,00:00:00,10.0,10,00:00:00
4,A14162943,SI,JR,66.0,100.0,00:00:00,33.0,100.0,00:00:00,42.0,...,00:00:00,5.0,10,00:00:00,5.0,10,00:00:00,6.0,10,00:00:00

In [28]:
proj.projects_total(grades)

Ellipsis

In [121]:
def only_proj(df):
    cols = df.columns
    project_cols = [x for x in cols if 'project' in x and '-' not in x and '_' not in x]
    for i in project_cols:
        df[i] = df[i].fillna(0)
    return df[project_cols]

In [122]:
def all_proj_detail(df):
    cols = df.columns
    project_cols = [x for x in cols if 'project' in x and 'check' not in x and 'Late' not in x]
    for i in project_cols:
        df[i] = df[i].fillna(0)
    return df[project_cols]

In [143]:
def projects_total(grades):
    '''
    projects_total that takes in grades and computes the total project grade
    for the quarter according to the syllabus. 
    The output Series should contain values between 0 and 1.
    
    :Example:
    >>> grades_fp = os.path.join('data', 'grades.csv')
    >>> grades = pd.read_csv(grades_fp)
    >>> out = projects_total(grades)
    >>> np.all((0 <= out) & (out <= 1))
    True
    >>> 0.7 < out.mean() < 0.9
    True
    '''
    project = only_proj(grades)
    all_proj = all_proj_detail(grades)
    # create empty dataframe to store project grades to later take the mean from
    scores_df = pd.DataFrame()
    for i in project.columns:
        # gets number of observations to create series of zeros for when there is no FR section
        size = len(all_proj[i])
        fr_score = pd.Series(np.zeros(shape = size))
        # set fr_max to zero in case no FR section
        fr_max = 0
        # gets a series of all projects scores and sets max_pts to max for that project
        proj_pts = all_proj[i]
        max_pts = all_proj[i + ' - Max Points'].max()
        # if there is a FR section, reassign fr variables to series of scores and max value
        if i + '_free_response' in all_proj.columns:
            fr_score = all_proj[i + '_free_response']
            fr_max = all_proj[i + '_free_response - Max Points'].max()
        # add project pts and fr pts. if no fr section, fr_score should be series of 0s and fr_max should be 0
        total_pts = proj_pts + fr_score
        total_max = max_pts + fr_max
        projects_total = total_pts / int(total_max)
        scores_df[i] = projects_total
    
    scores_df['mean'] = scores_df.mean(axis = 1)
    
    return scores_df['mean']

In [144]:
out = projects_total(grades)
#np.all((0 <= out) & (out <= 1))
0.7 < out.mean() < 0.9

True

### Computing lab grades

Now, you will clean and process the lab grades, which is a little more complicated. To do this, you will develop functions that:
- 'normalize' the grades, 
- adjust for late submissions, 
- drop the lowest lab grade, and 
- creates a total lab score for each student.

**Question 3**

Unfortunately, Gradescope sometimes experiences a delay in registering when an assignment is submitted during "periods of heavy usage" (i.e. near a submission deadline). You need to assess when a student's assignment was actually turned in on time, even if Gradescope did not process it in time. To do this, it is helpful to know:
* Every late submission has to be submitted by a TA (late submissions are turned off).
* TAs never submitted a late assignment "just after" the deadline. 
* The deadlines were at midnight and students had to come to staff hours to late-submit their assignment.

Create a function `last_minute_submissions` that takes in the dataframe `grades` and outputs the number of submissions on each assignment that were turned in on time by the student, yet marked 'late' by Gradescope. See the doctest for more details.

*Note:* You have to figure out what truly is a late submission by looking at the data and understanding the facts about the data generating process above. There is some ambiguity in finding which submissions are truly late; you will *make a best guess for a threshold* by looking at this dataset. This question is about 'cleaning' a messy 'data recording process'.

In [139]:
def only_labs(df):
    cols = df.columns
    lab_cols = [x for x in cols if 'lab' in x and '-' not in x and '_' not in x]
    for i in lab_cols:
        df[i] = df[i].fillna(0)
    return df[lab_cols]

In [140]:
def all_lab_detail(df):
    cols = df.columns
    lab_cols = [x for x in cols if 'lab' in x]
    for i in lab_cols:
        df[i] = df[i].fillna(0)
    return df[lab_cols]

In [141]:
only_labs = only_labs(grades)
only_labs.head()

   lab01  lab02  lab03  lab04  lab05  lab06  lab07  lab08  lab09
0   99.0   86.0   90.0   98.0   70.0   83.0   97.0   88.0   43.0
1   98.0   52.0   73.0   77.0   70.0   85.0   89.0   94.0   43.0
2   86.0   45.0   40.0   73.0   63.0   73.0   72.0   71.0   38.0
3  100.0  100.0   92.0   91.0   62.0   57.0  100.0   95.0   39.0
4   66.0   33.0   69.0   81.0   45.0   63.0   60.0   36.0   50.0

In [146]:
all_labs = all_lab_detail(grades)
all_labs

,lab01,lab01 - Max Points,lab01 - Lateness (H:M:S),lab02,lab02 - Max Points,lab02 - Lateness (H:M:S),lab03,lab03 - Max Points,lab03 - Lateness (H:M:S),lab04,...,lab06 - Lateness (H:M:S),lab07,lab07 - Max Points,lab07 - Lateness (H:M:S),lab08,lab08 - Max Points,lab08 - Lateness (H:M:S),lab09,lab09 - Max Points,lab09 - Lateness (H:M:S)
0,99.0,100.0,00:00:00,86.0,100.0,00:00:00,90.0,100.0,252:56:22,98.0,...,00:00:00,97.0,100.0,382:51:44,88.0,100.0,00:00:00,43.0,50.0,00:00:00
1,98.0,100.0,00:00:00,52.0,100.0,00:00:00,73.0,100.0,00:00:00,77.0,...,645:24:50,89.0,100.0,00:00:00,94.0,100.0,00:00:00,43.0,50.0,00:00:00
2,86.0,100.0,00:00:00,45.0,100.0,00:00:00,40.0,100.0,00:00:00,73.0,...,764:40:45,72.0,100.0,00:04:51,71.0,100.0,00:00:00,38.0,50.0,00:00:00
3,100.0,100.0,00:00:00,100.0,100.0,00:00:00,92.0,100.0,00:00:00,91.0,...,00:00:00,100.0,100.0,00:00:00,95.0,100.0,00:00:00,39.0,50.0,00:00:00
4,66.0,100.0,00:00:00,33.0,100.0,00:00:00,69.0,100.0,00:00:00,81.0,...,00:00:00,60.0,100.0,00:00:00,36.0,100.0,00:00:00,50.0,50.0,00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
530,100.0,100.0,47:26:10,82.0,100.0,00:00:00,100.0,100.0,00:00:00,88.0,...,431:48:42,76.0,100.0,00:00:00,91.0,100.0,00:00:00,49.0,50.0,00:00:13
531,100.0,100.0,00:00:00,86.0,100.0,00:00:00,80.0,100.0,00:00:00,62.0,...,00:00:00,85.0,100.0,00:00:00,84.0,100.0,00:00:00,28.0,50.0,00:00:00
532,87.0,100.0,00:00:00,90.0,100.0,00:00:00,100.0,100.0,00:00:00,99.0,...,00:00:00,95.0,100.0,00:00:00,87.0,100.0,00:00:00,50.0,50.0,00:00:00
533,84.0,100.0,00:00:00,83.0,100.0,00:00:00,88.0,100.0,00:00:00,93.0,...,419:06:41,77.0,100.0,00:00:00,95.0,100.0,00:00:00,41.0,50.0,00:00:00
534,90.0,100.0,00:00:00,75.0,100.0,00:00:00,92.0,100.0,00:00:00,81.0,...,00:00:00,98.0,100.0,00:00:00,79.0,100.0,00:00:00,30.0,50.0,00:00:00

In [160]:
def last_minute_submissions(grades):
    """
    last_minute_submissions takes in the dataframe 
    grades and a Series indexed by lab assignment that 
    contains the number of submissions that were turned 
    in on time by the student, yet marked 'late' by Gradescope.

    :Example:
    >>> fp = os.path.join('data', 'grades.csv')
    >>> grades = pd.read_csv(fp)
    >>> out = last_minute_submissions(grades)
    >>> isinstance(out, pd.Series)
    True
    >>> np.all(out.index == ['lab0%d' % d for d in range(1,10)])
    True
    >>> (out > 0).sum()
    8
    """ 
    
    # get late labs columns
    cols = grades.columns
    late_labs = [x for x in cols if 'Lateness' in x and 'lab' in x]
    assignment_dict = get_assignment_names(grades)
    labs = assignment_dict['lab']
    
    # get nubmer of labs
    n = len(late_labs)
    incorrect_late_count = []

    # threshhold s.t. labs turned in on time are still considered late
    threshhold = '02:30:00'
    
    # loop through all lab assignment late columns
    for lab in late_labs:
        # get num students that turned in the assingment past the deadline but before threshhold
        num_incorrect_late = len(grades[(grades[lab] < threshhold) & (grades[lab] > '00:00:00')])
        incorrect_late_count.append(num_incorrect_late)
        
        # changing the gradescope bug so that these students aren't penalized in Q4
        # bug_index = grades[(grades[lab] < threshhold) & (grades[lab] > '00:00:00')].index
        # grades[lab][bug_index] = '00:00:00'
        
    result = pd.Series(incorrect_late_count)
    result.index = labs
    return result

In [161]:
grades_fp = os.path.join('data', 'grades.csv')
grades = pd.read_csv(grades_fp)
out = last_minute_submissions(grades)
#isinstance(out, pd.Series)
#np.all(out.index == ['lab0%d' % d for d in range(1,10)])
(out > 0).sum()

8

**Question 4**

Now you need to adjust the lab grades for late submissions -- however, you need to take into account your investigation in the previous question, since students shouldn't be penalized by a bug in Gradescope!

Create a function `lateness_penalty` that takes in a 'Lateness' column and returns a column of penalties (represented by the values `1.0,0.9,0.8,0.5` according to the syllabus). Only *truly* late submissions should be counted as late.

*Note*: For the purpose of this project, we will only be calculating lateness for labs. There is no penalty for lateness for projects, discussions, nor checkpoints.

In [149]:
def all_lab_lateness(df):
    cols = df.columns
    lab_cols = [x for x in cols if 'lab' in x and 'Lateness' in x]
    for i in lab_cols:
        df[i] = df[i].fillna(0)
    return df[lab_cols]

In [151]:
all_late_labs = all_lab_lateness(grades)
all_late_labs.head()

,lab01 - Lateness (H:M:S),lab02 - Lateness (H:M:S),lab03 - Lateness (H:M:S),lab04 - Lateness (H:M:S),lab05 - Lateness (H:M:S),lab06 - Lateness (H:M:S),lab07 - Lateness (H:M:S),lab08 - Lateness (H:M:S),lab09 - Lateness (H:M:S)
0,00:00:00,00:00:00,252:56:22,00:00:00,00:00:00,00:00:00,382:51:44,00:00:00,00:00:00
1,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,645:24:50,00:00:00,00:00:00,00:00:00
2,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,764:40:45,00:04:51,00:00:00,00:00:00
3,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00
4,00:00:00,00:00:00,00:00:00,47:42:33,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00

In [176]:
def penalty(x):
    threshold = '02:30:00'
    if x < threshold:
        x = 1.0
    elif threshold < x <= '168:00:00':
        x = 0.9
    elif '168:00:00' < x <= '336:00:00':
        x = 0.8
    elif x > '336:00:00':
        x = 0.5
    return x

In [177]:
def lateness_penalty(col):
    """
    lateness_penalty takes in a 'lateness' column and returns 
    a column of penalties according to the syllabus.

    :Example:
    >>> fp = os.path.join('data', 'grades.csv')
    >>> col = pd.read_csv(fp)['lab01 - Lateness (H:M:S)']
    >>> out = lateness_penalty(col)
    >>> isinstance(out, pd.Series)
    True
    >>> set(out.unique()) <= {1.0, 0.9, 0.8, 0.5}
    True
    """

    penalties = col.apply(penalty)
    
    return penalties

In [178]:
fp = os.path.join('data', 'grades.csv')
col = pd.read_csv(fp)['lab01 - Lateness (H:M:S)']
out = lateness_penalty(col)
set(out.unique()) <= {1.0, 0.9, 0.8, 0.5}

True

**Question 5**

Create a function `process_labs` that takes in a dataframe like `grades` and returns a dataframe of processed lab scores. The output should:
* share the same index as `grades`,
* have columns given by the lab assignment names (e.g. `lab01,...lab10`)
* have values representing the lab grades for each assignment, adjusted for Lateness and scaled to a score between 0 and 1.

**Question 6**

Create a function `lab_total` that takes in dataframe of processed assignments (like the output of Question 5) and computes the total lab grade for each student according to the syllabus (returning a Series). Your answers should be proportions between 0 and 1. For example, if there are only 3 labs, and a student received scores of {80%,90%,100%}, then the total score would be 0.95.

*Note*: Don't forget to properly handle students who didn't turn in assignments! (Use your experience and common sense).

### Putting it together

**Question 7**

Finally, you need to create the final course grades. To do this, you will add up the total of each course component according to the weights given in the syllabus. 

* Create a function `total_points` that takes in `grades` and returns the final course grades according to the syllabus. Course grades should be proportions between zero and one.
* Create a function `final_grades` that takes in the final course grades as above and returns a Series of letter grades given by the standard cutoffs (`A >= .90`, `.90 > B >= .80`, `.80 > C >= .70`, `.70 > D >= .60`, `.60 > F`). You should not use rounding to determining the letter grades.
* Create a function `letter_proportions` which takes in the dataframe `grades` and outputs a Series that contains the proportion of the class that received each grade. (This question requires you to put everything together).
* The indices should be ordered by the proportion of the class that receives that grade, from largest to smallest.

*Note 1*: Don't repeat yourself when computing the checkpoint and discussion portions of the course.

*Note 2*: Only the lab portion of the course accounts for late assignments; you may assume all assignments in other portions are turned in without penalty.

*Note 3*: These values should add up to exactly 1.0. If you are getting something close such as 0.99999, that means there is a slight issue with your code from above. 

To check your work, verify the course grade distribution and relevant statistics! Do the work by hand for a few students.

### Do Sophomores get better grades?

**Question 8**

You notice that students who are sophomores on average did better in the class (if you can't verify this, you should go back and check your work!). Is this difference significant, or just due to noise?

Perform a hypothesis test, assessing likelihood of the null hypothesis: 
> "sophomores earn grades that are roughly equal on average to the rest of the class."


Create a function `simulate_pval` which takes in the number of simulations `N` and `grades` and returns the the likelihood that the grade of sophomores was no better on average than the class as a whole (i.e. calculate the p-value).

*Note:* To check your work, plot the sampling distribution and the observation. Do these values look reasonable?

### What is the true distribution of grades?

The gradebook for this class only reflects one particular instance of each student's performance, subject to the effects of all the little events and hiccups that occurred throughout the quarter. Might you have done better on the midterm had your roommate kept you up all night with their coughing? Wasn't it lucky that the example you were studying just before the final happened to appear on the exam?

**Question 9**

This question will simulate these '(un)lucky, random events' by adding or subtracting random amounts to each assignment before calculating the final grades. These 'random amounts' will be drawn from a Gaussian distribution of mean 0 and a std deviation 0.02:
```
np.random.normal(0, 0.02, size=(num_rows, num_cols))
```
Intuitively, such a model says that random events may bump up or down a given grade (given as a proportion):
- which on average has no effect on the class as a whole (mean 0),
- which not uncommonly might perturb a grade by 2% (std dev 0.02).

Create a function `total_points_with_noise` that takes in a dataframe like `grades`, adds noise to the assignments as described above, and returns the final scores using *the same procedure* as questions 1-7.

*Note:* You should be able to reuse (or minorly change) the code from previous problems. Try to be DRY (don't repeat yourself)!

*Note 1:* Once adding the noise to the assignment scores, use the `np.clip` function to be sure each assignment retains a score between 0% and 100%.

*Note 2:* To check your work -- what would you expect the difference between the actual scores and noisy scores to be, on average?

### Short-answer questions (hard-coded)

Use your functions from above to understanding the data and answer the following questions. The function below should return **hard-coded values**. It should not compute anything!

**Question 10**

Create a function `short_answer` of zero variables that returns (hard-coded) answers to the following question in a list:
0. For the class on average, what is the difference between students' scores (`total_points`) and their scores with noise (`total_points_with_noise`)? (Remark: plot the distribution of differences; does this align with what you know about binomial distributions?)
1. What percentage of the class only sees their grade change at most (but not including) $\pm 0.01$?
2. What is the 95% confidence interval for the statistic above? (see [DSC10](https://www.inferentialthinking.com/chapters/13/3/Confidence_Intervals.html) and use `np.percentile`)
3. What proportion of the class sees a change in their letter grade?
4. The assumption behind the model in Question 9 is that:
    - The (observed) gradebook well represents the true population of students,
    - The noisy scores represent other possible observations drawn from the true population of students.
    - Answer `True` or `False`

# Congratulations, you finished the project!

### Before you submit:
* Be sure you run the doctests on all your code in project01.py

### To submit:
* **Upload the .py file to gradescope**